version: '3.8'

services:
  db:
    container_name: onelinkdb
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5500:3306
    volumes:
      - onelinkdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: onelink
      MYSQL_USER: onelinkadmin
      MYSQL_PASSWORD: onelinkadminpass

volumes:
  onelinkdata:
